### ISSUE TITLE
@mixin only

### ISSUE THREAD

**Issue by mg901** [oddbird/accoutrement-layout#3]
It would not be bad to add mixin 'only'. If you do not mind, I could get it.

**Comment by mirisuzanne** [comment]
What would the `only` mixin do? How is it different from `between`?

**Comment by mg901** [comment]
$breakpoints: (
   xs: 0,    // 0px       Mobile first
   sm: 640,    // 640px   ~ Small tablet up 40em
   md: 800,    // 800px   ~ Large tablet up == 50em
   lg: 1200,   // 1024px  ~ Desktop up == 75em
   xl: 1600    // 1600px  ~ Large desktop up == 100em
  )

body {
  @include between(sm, lg) {
    background-color: red;
  }
}

// output
@media screen and (min-width: 40em) and (max-width: 99.9375em) {
  body {
      background-color: red;
   }
 }

body {
  @include only(sm) {
    background-color: red;
  }
}

// output
 @media screen and (min-width: 40em) and (max-width: 49.9375em) {
  body {
      background-color: red; 
  }
}

**Comment by mirisuzanne** [comment]
The logic here isn't obvious to me. Is it using `sm` as the minimum, and looking for the next-largest breakpoint in order to find the maximum?

I don't like it for a few reasons (but I'm open to more debate):

1. It encourages device-based breakpoints instead of content-based. Our breakpoints are all specific to components, so it wouldn't make sense to assume they relate to each other implicitly based on "next" size up or down.
2. Implicit relationships between breakpoints will more easily break when you add a new breakpoint, without a clear way to debug the problem. 
3. You can do the same already with `between(sm, md)`, a pretty minimal syntax difference, and much more explicit.

**Comment by mg901** [comment]
Yes, probably you are right.
